services:
  localai:
    image: localai/localai:v2.26.0-aio-gpu-nvidia-cuda-12
    # build:
    #   context: .
    #   dockerfile: Dockerfile-localai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
    volumes:
      - ./models:/build/models:cached
      - ./generated-images:/generated-images:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  inference-manager:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - localai
    environment:
      - LOCALAI_URL=http://localai:8080
      - DEBUG=true
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    depends_on:
      - inference-manager
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data: