services:
  localai:
    image: localai/localai:latest-gpu-nvidia-cuda-12
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
    volumes:
      - ./models:/build/models:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  inference-manager:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - localai
    volumes:
      - ./models:/app/models
    environment:
      - LOCALAI_URL=http://localai:8080
      - DEBUG=true
    restart: unless-stopped