version: '3.8'

services:
  localai:
    image: localai/localai:latest-gpu-nvidia-cuda-12
    ports:
      - "8080:8080"
    volumes:
      - ./models:/build/models
    environment:
      - DEBUG=true
      - MODELS_PATH=/build/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  inference-manager:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - localai
    volumes:
      - ./models:/app/models
    environment:
      - LOCALAI_URL=http://localai:8080
      - DEBUG=true
    restart: unless-stopped