services:
  inference-manager:
    build: .
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - STABILITY_MATRIX_URL=http://host.docker.internal:7861
      - OLLAMA_URL=http://host.docker.internal:11434
    restart: unless-stopped
    networks:
      - app-network

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    depends_on:
      - inference-manager
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - app-network

volumes:
  n8n_data:

networks:
  app-network:
    name: app-network
    driver: bridge
  default:
    external: false